### ISSUE TITLE
Remove varargs as command line variables

### ISSUE THREAD

**Issue by geloro94** [itcr-uni-luebeck/fhir-populator#14]
The varargs of the program i.e. for --package, cause https://github.com/koalaman/shellcheck/wiki/SC2086 when setting the args in bash:
python -m fhir_populator --endpoint "${BLAZE_SERVER_URL}" --get-dependencies --non-interactive --only-put --package ${PACKAGES}

Quoting ${PACKAGES} to resolve the issue is not possible, as the arguments are no longer interpreted as:
arg1 arg2 arg3
but instead as 
'arg1 arg2 arg3' 
which causes the application to crash.

**Comment by jpwiedekopf** [comment]
In ZSH and Bash, I was able to make the current implementation work by using a different syntax to define `$PACKAGES`:

```bash
export PACKAGES=("de.medizininformatikinitiative.kerndatensatz.person@1.0.16" "de.medizininformatikinitiative.kerndatensatz.medikation@1.0.11")
```

The syntax `("a" "b")` defines a list of strings, and this is expanded as required when calling FHIR Populator with this command line:

```bash
 python -m fhir_populator --endpoint $FHIR_SERVER_URL --get-dependencies --non-interactive --only-put --package $PACKAGES
```
