### ISSUE TITLE
Offline workflow when no internet connection is available

### ISSUE THREAD

**Issue by jpwiedekopf** [itcr-uni-luebeck/fhir-populator#16]
Some users may require a "sneaker-net" based approach for getting FHIR packages on the machine the FHIR Populator is running on, and can't use proxies. Support that use case by allowing retrieval of FHIR packages from a directory instead of downloading from a registry.

**Comment by geloro94** [comment]
Implemented in https://github.com/itcr-uni-luebeck/fhir-populator/commit/2b18b3a0c39d23feccc9334ec2dcce587eaec796
