### ISSUE TITLE
Don't include a Null ID into Resources

### ISSUE THREAD

**Issue by alexanderkiel** [itcr-uni-luebeck/fhir-populator#2]
While uploading resources without an ID, using POST, the resource send to the FHIR server includes a JSON `null` value for the `id` property. Blaze complains about this, which it shouldn't, but nevertheless you shouldn't send such resources in the first place. I'll fix this in https://github.com/samply/blaze/issues/370.

**Comment by jpwiedekopf** [comment]
Good catch, easily fixed :) Do you want to test this with Blaze before merging?

**Comment by alexanderkiel** [comment]
> Good catch, easily fixed :) Do you want to test this with Blaze before merging?

Thanks, it works in Blaze now!
